# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e51ce03c-a172-40b0-b80d-b31692c4d488'
  imageRepository: 'chackwebappocr'
  containerRegistry: 'akirainaks.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  buildcontext: ''

  # Kubernetes Namespace
  k8sNamespace: 'ocr'
  # k8sNamespaceForPR: 'ocr-pr'
  k8sNamespaceForPR: 'ocr-pr-$(System.PullRequest.PullRequestId)'
  imagePullSecret: 'akirainaks-acr-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Container'
  jobs:  
  - job: Build
    displayName: 'Build Docker Container'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(buildcontext)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: 'Deploy for Staging'
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to AKS'
    pool:
      vmImage: $(vmImageName)
    environment: 'chack411WebAppOCR2.$(k8sNamespace)'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: kubernetes-tasks.yml
            parameters:
              k8sNamespace: $(k8sNamespace)

- stage: Deploy_Production
  displayName: 'Deploy for Production'
  dependsOn: Deploy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: Deploy_Production
    displayName: 'Deploy to AKS'
    pool:
      vmImage: $(vmImageName)
    environment: 'chack411WebAppOCR2-Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploy to Production cluster...
            displayName: 'Deploy to Production cluster'

- stage: Deploy_PR
  displayName: 'Deploy for PR'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployPullRequest
    displayName: 'Deploy for Pull request'
    pool:
      vmImage: $(vmImageName)
    environment: 'chack411WebAppOCR2.$(k8sNamespaceForPR)'
    strategy:
      runOnce:
        deploy:
          steps:
          - reviewApp: $(k8sNamespace)

          - task: Kubernetes@1
            displayName: 'Create a new namespace for the pull request'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'

          - template: kubernetes-tasks.yml
            parameters:
              k8sNamespace: $(k8sNamespaceForPR)
          
          - task: Kubernetes@1
            name: get
            displayName: 'Get services in the new namespace'
            continueOnError: true
            inputs:
              command: get
              namespace: $(k8sNamespaceForPR)
              arguments: svc
              outputFormat: jsonpath='http://{.items[0].status.loadBalancer.ingress[0].ip}:{.items[0].spec.ports[0].port}'
              
          # Getting the IP of the deployed service and writing it to a variable for posing comment
          - script: |
              url="$(get.KubectlOutput)"
              message="Your review app has been deployed"
              if [ ! -z "$url" -a "$url" != "http://:" ] 
              then
                message="${message} and is available at $url"
              fi
              echo "##vso[task.setvariable variable=GITHUB_COMMENT]$message"
