apiVersion : apps/v1
kind: Deployment
metadata:
  name: chackwebappocr 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chackwebappocr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chackwebappocr 
    spec:
      containers:
      - name: chackwebappocr 
        image: akirainaks.azurecr.io/chackwebappocr
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
        imagePullPolicy: Always
        env:
        - name: Noodle_Prediction_Key
          valueFrom:
            secretKeyRef:
              name: cogapi-secret
              key: Noodle_Prediction_Key
        - name: Vision_API_Subscription_Key
          valueFrom:
            secretKeyRef:
              name: cogapi-secret
              key: Vision_API_Subscription_Key
